# Generated by Django 3.2.4 on 2021-07-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=300, null=True)),
                ('choice1', models.CharField(max_length=300, null=True)),
                ('choice2', models.CharField(max_length=300, null=True)),
                ('choice3', models.CharField(max_length=300, null=True)),
                ('choice4', models.CharField(max_length=300, null=True)),
                ('answer', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
