# Generated by Django 3.2.4 on 2021-07-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_rename_ques_questionsmodel_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=100)),
                ('MarksObtained', models.IntegerField()),
            ],
        ),
    ]
