# Generated by Django 3.2.4 on 2021-07-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20210722_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseName',
            new_name='course_name',
        ),
    ]
